export const POP_BALLOON = 'positions/POP_BALLOON';
export const ADD_BALLOON = 'positions/ADD_BALLOON';

export const popBalloon = (id) => ({
  type: POP_BALLOON,
  id,
});

export const addBalloon = (balloon) => ({
  type: ADD_BALLOON,
  balloon,
});

const initialState = [
  {
    id: 1,
    top: 90,
    left: 30,
    scale: 1.5,
    rotate: 150,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-less',
    tip: false,
    show: true,
  },
  {
    id: 2,
    top: 52,
    left: 15,
    scale: 0.65,
    rotate: 160,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-less',
    tip: false,
    show: true,
  },
  {
    id: 3,
    top: 58,
    left: 69,
    scale: 3,
    rotate: 33,
    color: '#F31C12',
    shape: 'heart',
    type: 'enlarge',
    tip: false,
    show: true,
  },
  {
    id: 4,
    top: 33,
    left: 2,
    scale: 0.8,
    rotate: 20,
    color: 'brown',
    shape: 'bear',
    type: 'shake-bear-noTip',
    tip: false,
    show: true,
  },
  {
    id: 5,
    top: 14,
    left: 29,
    scale: 1.3,
    rotate: 150,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 6,
    top: -23,
    left: 15,
    scale: 0.9,
    rotate: -50,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-daisy-noTip',
    tip: false,
    show: true,
  },
  {
    id: 7,
    top: 14,
    left: 12,
    scale: 1.2,
    rotate: 180,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 8,
    top: 0,
    left: 16,
    scale: 0.8,
    rotate: 15,
    color: '#3110C0',
    shape: 'bear',
    type: 'shake-bear-noTip',
    tip: false,
    show: true,
  },
  {
    id: 9,
    top: 12,
    left: 21,
    scale: 1.15,
    rotate: 140,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 10,
    top: -1,
    left: 22,
    scale: 1.2,
    rotate: -15,
    color: '#A7DD2D',
    shape: 'heart',
    type: 'shake-bear-noTip',
    tip: false,
    show: true,
  },
  {
    id: 11,
    top: 21,
    left: 4,
    scale: 0.8,
    rotate: 115,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 12,
    top: 13,
    left: 7,
    scale: 1.3,
    rotate: 130,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 13,
    top: -15,
    left: 36,
    scale: 0.9,
    rotate: -30,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-daisy-noTip',
    tip: false,
    show: true,
  },

  {
    id: 14,
    top: -11,
    left: 27,
    scale: 0.9,
    rotate: -70,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-daisy-noTip',
    tip: false,
    show: true,
  },
  {
    id: 15,
    top: 13,
    left: 4,
    scale: 1.3,
    rotate: 130,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 16,
    top: 13,
    left: 5,
    scale: 1.3,
    rotate: -35,
    color: '#F31C12',
    shape: 'heart',
    type: 'shake-heart-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 17,
    top: 21,
    left: 12,
    scale: 0.9,
    rotate: 160,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 18,
    top: 33,
    left: 21,
    scale: 0.8,
    rotate: 115,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-less',
    tip: false,
    show: true,
  },
  {
    id: 19,
    top: 29,
    left: 8,
    scale: 0.8,
    rotate: 180,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-less',
    tip: false,
    show: true,
  },
  {
    id: 20,
    top: 17,
    left: 16,
    scale: 0.7,
    rotate: 130,
    color: '#FCBB11',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },

  {
    id: 21,
    top: 27,
    left: 17,
    scale: 1,
    rotate: 120,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 22,
    top: 18,
    left: 26,
    scale: 0.8,
    rotate: -40,
    color: '#3110C0',
    shape: 'bear',
    type: 'shake-bear-noTip',
    tip: false,
    show: true,
  },
  {
    id: 23,
    top: 16,
    left: 37,
    scale: 1.3,
    rotate: 160,
    color: '#FCBB11',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 24,
    top: 30,
    left: 24,
    scale: 1.2,
    rotate: 165,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 25,
    top: 25,
    left: 32,
    scale: 1.3,
    rotate: 135,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 26,
    top: 6,
    left: 30,
    scale: 0.8,
    rotate: -25,
    color: '#FF84AA',
    shape: 'bear',
    type: 'shake-bear-noTip',
    tip: false,
    show: true,
  },
  {
    id: 27,
    top: 37,
    left: 27,
    scale: 1.1,
    rotate: 190,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 28,
    top: 65,
    left: 38,
    scale: 0.9,
    rotate: 175,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip',
    tip: false,
    show: true,
  },
  {
    id: 29,
    top: 64,
    left: 44,
    scale: 1.1,
    rotate: 175,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-tip',
    tip: false,
    show: true,
  },
  {
    id: 30,
    top: 57,
    left: 50,
    scale: 1.3,
    rotate: 170,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-tip',
    tip: false,
    show: true,
  },
  {
    id: 31,
    top: 50,
    left: 51,
    scale: 1.3,
    rotate: 180,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip',
    tip: false,
    show: true,
  },
  {
    id: 32,
    top: 40,
    left: 36,
    scale: 1.2,
    rotate: 165,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 33,
    top: 41,
    left: 32,
    scale: 0.9,
    rotate: 140,
    color: '#FCBB11',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 34,
    top: 48,
    left: 36,
    scale: 1.2,
    rotate: 110,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 35,
    bottom: -315,
    right: -338,
    scale: 1,
    rotate: 135,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-more',
    tip: true,
    show: true,
  },
  {
    id: 36,
    top: 2,
    left: 41,
    scale: 0.8,
    rotate: -85,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-daisy-noTip',
    tip: false,
    show: true,
  },
  {
    id: 37,
    top: 51,
    left: 40,
    scale: 1,
    rotate: 145,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 38,
    bottom: 130,
    right: 328,
    scale: 0.8,
    rotate: -35,
    color: '#FF84AA',
    shape: 'bear',
    type: 'shake-bear-tip',
    tip: true,
    show: true,
  },
  {
    id: 39,
    top: 40,
    left: 42,
    scale: 1.2,
    rotate: 190,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 40,
    top: 29,
    left: 42,
    scale: 0.95,
    rotate: 140,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 41,
    top: 24,
    left: 38,
    scale: 1.1,
    rotate: -20,
    color: '#A7DD2D',
    shape: 'heart',
    type: 'shake-bear-noTip',
    tip: false,
    show: true,
  },
  {
    id: 42,
    top: 58,
    left: 51,
    scale: 1.1,
    rotate: 170,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-tip',
    tip: false,
    show: true,
  },
  {
    id: 43,
    top: 15,
    left: 50,
    scale: 1.3,
    rotate: 190,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 44,
    top: 22,
    left: 48,
    scale: 1.4,
    rotate: 180,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip',
    tip: false,
    show: true,
  },
  {
    id: 45,
    top: -17,
    left: 73,
    scale: 0.8,
    rotate: -10,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-heart-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 46,
    top: 22,
    left: 70,
    scale: 1.1,
    rotate: 190,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 47,
    top: 12,
    left: 68,
    scale: 0.7,
    rotate: 200,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 48,
    top: 11,
    left: 94,
    scale: 0.8,
    rotate: 190,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 49,
    top: 1,
    left: 85,
    scale: 1,
    rotate: 260,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip-right-more',
    tip: false,
    show: true,
  },
  {
    id: 50,
    top: -6,
    left: 84,
    scale: 0.7,
    rotate: 70,
    color: '#F31C12',
    shape: 'bear',
    type: 'shake-bear-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 51,
    top: 2,
    left: 80,
    scale: 1,
    rotate: 250,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 52,
    top: 17,
    left: 76,
    scale: 1.3,
    rotate: 220,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 53,
    top: 20,
    left: 82,
    scale: 0.8,
    rotate: 245,
    color: '#FCBB11',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 54,
    top: 27,
    left: 90,
    scale: 0.8,
    rotate: 225,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 55,
    top: 21,
    left: 76,
    scale: 0.85,
    rotate: 255,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 56,
    top: 21,
    left: 67,
    scale: 0.9,
    rotate: 200,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 57,
    top: 32,
    left: 71,
    scale: 1,
    rotate: 190,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 58,
    top: 11,
    left: 63,
    scale: 1,
    rotate: 200,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-noTip-right-more',
    tip: false,
    show: true,
  },
  {
    id: 59,
    top: 13,
    left: 59,
    scale: 1.2,
    rotate: 210,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 60,
    top: 19,
    left: 58,
    scale: 1.1,
    rotate: 250,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 61,
    top: 8,
    left: 58,
    scale: 0.7,
    rotate: 220,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 62,
    top: 14,
    left: 57,
    scale: 0.9,
    rotate: 225,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 63,
    top: -10,
    left: 57,
    scale: 0.8,
    rotate: -15,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-heart-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 64,
    top: 10,
    left: 51,
    scale: 1.4,
    rotate: 10,
    color: '#FCBB11',
    shape: 'heart',
    type: 'shake-heart-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 65,
    bottom: -310,
    right: -510,
    scale: 1.1,
    rotate: -30,
    color: '#FF84AA',
    shape: 'daisy',
    type: 'shake-daisy-tip',
    tip: true,
    show: true,
  },
  {
    id: 66,
    top: 50,
    left: 47,
    scale: 0.8,
    rotate: 210,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 67,
    top: 44,
    left: 45,
    scale: 0.65,
    rotate: 220,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: false,
    show: true,
  },
  {
    id: 68,
    bottom: -69,
    right: -8,
    scale: 0.8,
    rotate: 180,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-tip-right',
    tip: true,
    show: true,
  },
  {
    id: 69,
    bottom: -361,
    right: -130,
    scale: 1.2,
    rotate: 160,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip',
    tip: true,
    show: true,
  },
  {
    id: 70,
    top: 35,
    left: 55,
    scale: 0.9,
    rotate: 190,
    color: '#F31C12',
    shape: 'round',
    type: 'shake-bottom-noTip-right-more',
    tip: false,
    show: true,
  },
  {
    id: 71,
    top: 23,
    left: 60,
    scale: 0.8,
    rotate: 45,
    color: '#FF84AA',
    shape: 'bear',
    type: 'shake-bear-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 72,
    top: 36,
    left: 70,
    scale: 0.8,
    rotate: 155,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-noTip-right-more',
    tip: false,
    show: true,
  },
  {
    id: 73,
    top: 11,
    left: 59,
    scale: 1,
    rotate: 35,
    color: '#F31C12',
    shape: 'heart',
    type: 'shake-heart-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 74,
    bottom: 82,
    right: 48,
    scale: 0.9,
    rotate: 200,
    color: '#A7DD2D',
    shape: 'round',
    type: 'shake-bottom-tip-right2',
    tip: true,
    show: true,
  },
  {
    id: 75,
    bottom: -404,
    right: -192,
    scale: 0.9,
    rotate: 232,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip-right-more',
    tip: true,
    show: true,
  },
  {
    id: 76,
    bottom: 0,
    right: -145,
    scale: 0.9,
    rotate: 220,
    color: '#FCBB11',
    shape: 'round',
    type: 'shake-bottom-tip-right2',
    tip: true,
    show: true,
  },
  {
    id: 77,
    bottom: -339,
    right: -95,
    scale: 0.9,
    rotate: 218,
    color: '#3110C0',
    shape: 'round',
    type: 'shake-bottom-tip-right-more',
    tip: true,
    show: true,
  },
  {
    id: 78,
    bottom: -314,
    right: -242,
    scale: 1.2,
    rotate: 205,
    color: '#FF84AA',
    shape: 'round',
    type: 'shake-bottom-tip-right-more',
    tip: true,
    show: true,
  },
  {
    id: 79,
    top: 0,
    left: 74,
    scale: 1.3,
    rotate: 35,
    color: '#F31C12',
    shape: 'heart',
    type: 'shake-heart-noTip-right',
    tip: false,
    show: true,
  },
  {
    id: 80,
    bottom: 220,
    right: -239,
    scale: 1.1,
    rotate: 20,
    color: '#F31C12',
    shape: 'heart',
    type: 'shake-heart-tip-right',
    tip: true,
    show: true,
  },
  {
    id: 81,
    top: 86,
    left: 67,
    scale: 0.5,
    rotate: 20,
    color: '#F31C12',
    shape: 'daisy',
    type: 'shake-bottom-less',
    tip: false,
    show: true,
  },
];

export default function positions(state = initialState, action) {
  switch (action.type) {
    case POP_BALLOON:
      return state.map((balloon) =>
        balloon.id === action.id ? { ...balloon, show: !balloon.show } : balloon
      );
    case ADD_BALLOON:
      return [...state, action.balloon];
    default:
      return state;
  }
}
